name: ci

on:
  push:
    branches: main

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set the value
        id: step_one
        run: |
          echo "action_state=yellow" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          # platforms: linux/amd64,linux/arm64,linux/386
          platforms: linux/amd64
          push: true
          tags: syoh/app:${{ env.action_state }}

      - name: Generate conda package lists
        run: |
          docker run -i --rm syoh/app:${{ env.action_state }} bash -c 'conda list --explicit' > requirement.txt
          docker run -i --rm syoh/app:${{ env.action_state }} bash -c 'conda env export -n base' | sed 's/name: base/name: otter-gradescope-env/' | grep -v '^prefix' > environment.yml
          cat requirement.txt
          cat environment.yml

